### ISSUE TITLE
dockerhub debian branch 7.3.11 builds absent

### ISSUE THREAD

**Issue by sheershoff** [bscheshirwork/docker-php#2]
Thank you for your work.

Can you please consider restoring dockerhub autobuilding for your dockerfiles? Or at least also build for debian 7.3.11-alpine-4yii2-xdebug ?

Thank you )

**Comment by bscheshirwork** [comment]
something wrong happens with autobuild on docker hub ...

So... I run build `bscheshir/php:7.3.11-fpm-4yii2` manually now.

...and `bscheshir/php:7.3.11-fpm-4yii2-xdebug` now

**Comment by sheershoff** [comment]
Thank you very much! D
